/// <reference path= "./universe.ts" />
var canvas = document.createElement("canvas");
canvas.id = "canvas-giratorio";
canvas.style.backgroundColor = "white";
canvas.style.border = "1px solid black";
canvas.style.width = "1000px";
canvas.style.height = "800px";
var ctx = canvas.getContext("2d");
canvas.width = 800;
canvas.height = 800;
ctx.imageSmoothingEnabled = false;
document.body.appendChild(canvas);
var vrp_camera = new Dot(0, 0.4, 1);
var focal_point_camera = new Dot(0, 0, 0);
var distance_point = 240;
var camera = new Camera(vrp_camera, focal_point_camera, distance_point, 0, 0, canvas_width, canvas_height);
// constructor(view_reference_point: Dot, focal_p: Dot, dp: number, wid: number, heig: number, min_x: number, min_y: number, max_x: number, max_y: number){
var uni = new Universe(ctx, camera);
// let A = new Dot(-10, -20, 10);
// let B = new Dot(10, -20, 10);
// let C = new Dot(7, 20, 10);
// let D = new Dot(-7, 20, 10);
// let E = new Dot(10, -20, -10);
// let F = new Dot(7, 20, -10);
// let G = new Dot(-7, 20, -10);
// let H = new Dot(-10, -20, -10);
// let pyramid_dots: Array<Dot>;
// pyramid_dots = [A, B, C, D, E, F, G, H];
// let pyramid = new Obj_3D("blue", pyramid_dots);
// uni.add_obj(pyramid);
var A = new Dot(-7.5, -0.75, 2.25);
var B = new Dot(-3.5, -4.75, 6.25);
var C = new Dot(3.5, 4.25, -9.75);
var D = new Dot(7.5, 1.25, 1.25);
var E = new Dot(16, 10, -5);
var F = new Dot(16, 10, -20);
var control_dots;
var other_dots;
var control_dots_2;
var control_dots_3;
control_dots = [A, B, C, D];
control_dots_2 = [B, C, D, E];
control_dots_3 = [C, D, E, F];
other_dots = [B, D, A, C];
var spline = new Spline(control_dots);
var spline_2 = new Spline(control_dots_2);
var spline_3 = new Spline(control_dots_3);
var other = new Spline(other_dots);
var surface_01 = new Surface(4, 4, 3, 3, 10, 10);
// print_matriz(surface_01.get_cp_as_mat(), "Teste 01")
// uni.add_obj_spline(spline);
surface_01.generateSurface();
// print_matriz(surface_01.get_outp_as_mat(), "Teste 02")
// surface_01.displaySurface();
// uni.add_obj_spline(spline_2);
// uni.add_obj_spline(spline_3);
// uni.add_obj_spline(other);
uni.add_surface(surface_01);
uni.animate_world();
